Feature: Properties of components in Mobile Wise


  Scenario Outline: Validation and Verification Of Properties Side Bar


    Given Entered a valid <username> <password>
    When  Clicked on the sign in button
    And  Validate login <expected_output>
    And Create A Project
    And Clicked on the Project
    And Click on the <application_type>
    And Enter <app_name> <application_name_field_message> <app_desc> and Click next <themes_dropdown> <headings_dropdown> <body_dropdown> <suggestion_message> and Click on Next
    Then Validate Application Created <toaster_message> <app_name>
    And Click on the Pages Module, Click on the Landing Page and click on the Add Component Button
    And Click on the <components_panel> and drag the <component> to the screen builder <offset_value_x> <offset_value_y>
    And Verify the <component> on the screen builder
    And Verify <component> sidebar and Validate Back button Functionality
    And Verify Panels in the Properties side bar <panels>
    And Edit <properties> Of the components in different panels and click on Update Component Button <panels> <values_comp> <component>





    Examples:
      | username | password     | expected_output | application_type | app_name      | application_name_field_message | app_desc                       | themes_dropdown | headings_dropdown | body_dropdown | suggestion_message        | toaster_message                    | components_panel | component      | offset_value_x | offset_value_y | panels                                                  | properties                                                                                        | values_comp                                                        |
#      | "dummy"  | "1234567890" | "Projects"      | " Mobile App "   | "Demo Mobile" | "Application name available."  | "Demo Application Description" | "Pink Light"    | "Roboto Flex"     | "Roboto Flex" | "This is required field!" | "Sucessfully Created Application " | "Form Fields"    | "Scanner"      | "500"          | "0"            | "Scanner Property,Validation"                           | "Display Type,Label,Top Margin,Validation Type"                                                   | "outlined,Barcode Scanner,20,Required"                             |
#      | "dummy"  | "1234567890" | "Projects"      | " Mobile App "   | "Demo Mobile" | "Application name available."  | "Demo Application Description" | "Pink Light"    | "Roboto Flex"     | "Roboto Flex" | "This is required field!" | "Sucessfully Created Application " | "Form Fields"    | "Image"        | "500"          | "0"            | "Image Property,Validation"                             | "Image,Top Margin,Select Action Type"                                                             | "D:\\MobileWise\\Logo\\logo2.webp,20,Navigation"                   |
#      | "dummy"  | "1234567890" | "Projects"      | " Mobile App "   | "Demo Mobile" | "Application name available."  | "Demo Application Description" | "Pink Light"    | "Roboto Flex"     | "Roboto Flex" | "This is required field!" | "Sucessfully Created Application " | "Form Fields"    | "Text"         | "500"          | "0"            | "Text Properties,Click Actions"                         | "Text,Position,Top Margin,Formatting Styles,Select Action Type"                                   | "Display Text,center,20,true-false-false-20,Navigation"            |
##      | "dummy"  | "1234567890" | "Projects"      | " Mobile App "   | "Demo Mobile" | "Application name available."  | "Demo Application Description" | "Pink Light"    | "Roboto Flex"     | "Roboto Flex" | "This is required field!" | "Sucessfully Created Application " | "Form Fields"    | "Radio Button" | "500"          | "0"            | "Input Properties,Click Actions,Validation"             | "Title,Label,Top Margin,Select Action Type,Validation Type"                                       | "Gender,Male-Female-NA_true-Other_false,20,Navigation,Required"    |
##      | "dummy"  | "1234567890" | "Projects"      | " Mobile App "   | "Demo Mobile" | "Application name available."  | "Demo Application Description" | "Pink Light"    | "Roboto Flex"     | "Roboto Flex" | "This is required field!" | "Sucessfully Created Application " | "Form Fields"    | "Check Box"    | "500"          | "0"            | "Input Properties,Click Actions,Validation"             | "Label,Top Margin,Select Action Type,Validation Type"                                             | "Are You Happy,20,Navigation,Required"                             |
#      | "dummy"  | "1234567890" | "Projects"      | " Mobile App "   | "Demo Mobile" | "Application name available."  | "Demo Application Description" | "Pink Light"    | "Roboto Flex"     | "Roboto Flex" | "This is required field!" | "Sucessfully Created Application " | "Form Fields"    | "File Picker"  | "500"          | "0"            | "File Properties,Validation"                            | "Display Type,Label,Top Margin,File Types,Max Size,Preview File,File Compression,Validation Type" | "outlined,Upload File,20,PDF,100,true,false,Required"              |
##      | "dummy"  | "1234567890" | "Projects"      | " Mobile App "   | "Demo Mobile" | "Application name available."  | "Demo Application Description" | "Pink Light"    | "Roboto Flex"     | "Roboto Flex" | "This is required field!" | "Sucessfully Created Application " | "Form Fields"    | "Text Field"   | "500"          | "0"            | "Input Properties,Validation"                           | "Display Type,Label,Data Type,PlaceHolder,Top Margin,Validation Type"                             | "outlined,First Name,text,Enter Name,20,Required"                  |
##      | "dummy"  | "1234567890" | "Projects"      | " Mobile App "   | "Demo Mobile" | "Application name available."  | "Demo Application Description" | "Pink Light"    | "Roboto Flex"     | "Roboto Flex" | "This is required field!" | "Sucessfully Created Application " | "Form Fields"    | "Drop Down"    | "500"          | "0"            | "Input Properties,Validation,Data Source,Click Actions" | "Display Type,Label,Dropdown Type,Top Margin,Validation Type,Drop Down Type,Select Action Type"   | "outlined,Nationality,Single Select,20,Required,Manual,Navigation" |
##      | "dummy"  | "1234567890" | "Projects"      | " Mobile App "   | "Demo Mobile" | "Application name available."  | "Demo Application Description" | "Pink Light"    | "Roboto Flex"     | "Roboto Flex" | "This is required field!" | "Sucessfully Created Application " | "Form Fields"    | "Media Upload" | "500"          | "0"            | "Image/Video Properties,Validation"                     | "Display Type,Label,Top Margin,Upload Type,Validation Type"                                       | "outlined,Upload Image,20,image_JPEG_1_true_true_true,Required"    |
#      | "dummy"  | "1234567890" | "Projects"      | " Mobile App "   | "Demo Mobile" | "Application name available."  | "Demo Application Description" | "Pink Light"    | "Roboto Flex"     | "Roboto Flex" | "This is required field!" | "Sucessfully Created Application " | "Form Fields"    | "Media Upload" | "500"          | "0"            | "Image/Video Properties,Validation"                     | "Display Type,Label,Top Margin,Upload Type,Validation Type"                                       | "outlined,Upload Image,20,imgDirection,Required"                   |
#      | "dummy"  | "1234567890" | "Projects"      | " Mobile App "   | "Demo Mobile" | "Application name available."  | "Demo Application Description" | "Pink Light"    | "Roboto Flex"     | "Roboto Flex" | "This is required field!" | "Sucessfully Created Application " | "Form Fields"    | "Date Picker"  | "500"          | "0"            | "Date Picker Properties,Validation"                     | "Display Type,Label,Top Margin,Validation Type"                                                   | "outlined,Date Of Birth,20,Required"                               |
#      | "dummy"  | "1234567890" | "Projects"      | " Mobile App "   | "Demo Mobile" | "Application name available."  | "Demo Application Description" | "Pink Light"    | "Roboto Flex"     | "Roboto Flex" | "This is required field!" | "Sucessfully Created Application " | "Form Fields"    | "Range Picker" | "500"          | "0"            | "Range Picker Properties,Validation"                    | "Display Type,Label,Top Margin,Select Date Format,MinDays,maxDays,Validation Type"                | "outlined,Date From and To,20,dd/MM/yyyy,1,5,Required"             |
#      | "dummy"  | "1234567890" | "Projects"      | " Mobile App "   | "Demo Mobile" | "Application name available."  | "Demo Application Description" | "Pink Light"    | "Roboto Flex"     | "Roboto Flex" | "This is required field!" | "Sucessfully Created Application " | "Buttons"        | "Save"         | "500"          | "0"            | "Button Styling,Click Actions"                          | "Display Type,Text,Top Margin,Formatting Styles,Select Action Type"                               | "filled,Submit,20,true-false-false-18,Navigation"                  |
#      | "dummy"  | "1234567890" | "Projects"      | " Mobile App "   | "Demo Mobile" | "Application name available."  | "Demo Application Description" | "Pink Light"    | "Roboto Flex"     | "Roboto Flex" | "This is required field!" | "Sucessfully Created Application " | "Add Ons"        | "Separator"    | "500"          | "0"            | "Separator Property"                                    | "Thickness,Top Margin"                                                                            | "100,50"                                                           |
#      | "dummy"  | "1234567890" | "Projects"      | " Mobile App "   | "Demo Mobile" | "Application name available."  | "Demo Application Description" | "Pink Light"    | "Roboto Flex"     | "Roboto Flex" | "This is required field!" | "Sucessfully Created Application " | "Add Ons"        | "Geotag"       | "500"          | "0"            | "Geo Property,Validation"                               | "Label,Top Margin,Validation Type"                                                                | "Live Location,20,Required"                                        |
#      | "dummy"  | "1234567890" | "Projects"      | " Mobile App "   | "Demo Mobile" | "Application name available."  | "Demo Application Description" | "Pink Light"    | "Roboto Flex"     | "Roboto Flex" | "This is required field!" | "Sucessfully Created Application " | "Add Ons"        | "Geofence"     | "500"          | "0"            | "Geofence Property,Validation"                          | "Label,Top Margin,Select GeoFence Type,Select GeoFence Shape,Validation Type"                     | "Pole Location,20,walking,line,Required"                           |
      | "dummy"  | "1234567890" | "Projects"      | " Mobile App "   | "Demo Mobile" | "Application name available."  | "Demo Application Description" | "Pink Light"    | "Roboto Flex"     | "Roboto Flex" | "This is required field!" | "Sucessfully Created Application " | "Add Ons"        | "Address"      | "500"          | "0"            | "Address Properties,Validation"                         | "Display Type,Label,PlaceHolder,Top Margin,Validation Type"                                       | "outlined,City Name,Enter Present City Name...,20,Required"        |






